language: generic
sudo: required

service:
  - docker

before_install:
  - docker build -t cnkay/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cnkay/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-188310139991"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
